
###    ===================== CREATE =====================
POST http://localhost:8080/user
Content-Type: application/json
Accept: application/json

{
  "name": "John"
}

<> 2023-11-25T173347.201.json
<> 2023-11-25T173205.201.json
<> 2023-11-25T173024.201.json




###    ===================== GET BY ID =====================
GET http://localhost:8080/user/1158666086




###   ===================== NOTIFY =====================
POST http://localhost:8080/user/1158666086/notify
Content-Type: application/json

{
  "message": "Hello, world!"
}



###   ===================== CREATE MULTIPLE =====================
POST http://localhost:8080/user/multiple
Content-Type: application/json

[
  {
    "name": "Bill"
  },
  {
    "name": "Jack"
  },
  {
    "name": "Maria"
  }
]

<> 2023-11-25T174207.201.json
<> 2023-11-25T173950.201.json
<> 2023-11-25T173659.409.json
<> 2023-11-25T171118.201.json




###    ===================== GET ALL =====================
GET http://localhost:8080/user/all

<> 2023-11-25T174216.200.json
<> 2023-11-25T165626.200.json
<> 2023-11-25T165454.200.json


###    ===================== DELETE MULTIPLE =====================
DELETE http://localhost:8080/user/multiple?ids=1594002406,1321235856,1313852230
